#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server
if [[$# -1t 3 ]];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY" >&2
    exit 2
else
     scp -i "$4" -o "StrictHOSTKEYCHECKIG no" "$1" "$3"@"$2":~/
fi

