#!/usr/bin/env bash
#Install nginx web server
sudo apt update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html

"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index.html index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
}"

	service nginx restart
fi

