#!/usr/bin/env bash
# install nginx and add a custom header
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html /var/www/error
chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
echo -e "Ceci n\x27est pas une page" > /var/www/error/404.html

# configuration
SCONFIG=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
                add_header X-Served-By \$hostname;
        }
        if (\$request_filename ~ redirect_me){
                rewrite ^ https://m.facebook.com/ashaju.ronke permanent;
        }
        error_page 404 /404.html;
        location = /404.html {
                root /var/www/error/;
                internal;
                add_header X-Served-By \$hostname;
        }
}"

bash -c "echo -e '$SCONFIG' > /etc/nginx/sites-enabled/default"

# server
if [ "$(pgrep -c nginx)" -le 0 ]; then
        service nginx start
else
        service nginx restart
fi

