#!/usr/bin/env bash
# Installing a new server for content
./0-nginx_likes_port_80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
